max_velocity = 1.5 #m/s
max_acceleration = 1.3 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 5.35 #approximation, will probably need tweaking
    y = 2.18
    angle = 180.0

[end_pose]
    x = 3.93
    y = 2.18
    angle = 180.0

[[internal_points]]
    x = 4.8
    y = 2.18