max_velocity = 1.5 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.0 #7
    y = 4.68 #4.58 ->4.48
    angle = 180.0
[end_pose]
    x = 5.0 #5.1 
    y = 3.25
    angle = 0.0
[[internal_points]]
    x = 6.71
    y = 3.5