max_velocity = 1.5 #m/s
max_acceleration = 1.25 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02
    y = 2.75
    angle = 0.0

[end_pose]
    x = 3.00 # FIXME guess
    y = 2.75
    angle = 0.0

[[internal_points]]
    x = 2.50 # midpoint
    y = 2.75 # midpoint

