max_velocity = 1.5 #m/s
max_acceleration = 1.25 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02
    y = 2.24
    angle = 0.0

[end_pose]
    x = 7.57 
    y = 2.04
    angle = 0.0

[[internal_points]]
    x = 4.55 # midpoint
    y = 2.19 # midpoint

