max_velocity = 1.0 #m/s
max_acceleration = 0.80 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 0.691
    y = 7.51
    angle = 0.0

[end_pose]
    x = 6.04
    y = 6.86
    angle = 0.0

[[internal_points]]
    x = 3.5
    y = 7.32